environment:
  matrix:
    - node_version: "8"

branches:
  only:
  - master

install:
  - ps: Install-Product node $env:node_version
  - yarn install --frozen-lockfile

build: off

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"
