environment:
  matrix:
    - node_version: "8"
    - node_version: "6"
    - node_version: "4"

branches:
  only:
  - master

install:
  - ps: Install-Product node $env:node_version
  - yarn install --frozen-lockfile

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"
